import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { loadFamilyMembers } from './familyService';

export function exportUserManualPDF() {
  const doc = new jsPDF();
  doc.setFont('helvetica');
  doc.setFontSize(18);
  doc.text('Relationship User Manual', 14, 20);
  doc.setFontSize(12);
  doc.text('Generated by DEFRAG', 14, 28);

  const members = loadFamilyMembers();
  if (!members.length) {
    doc.text('No family data found.', 14, 40);
  } else {
    const rows = members.map(m => [
      m.name,
      m.relationship,
      m.birthDate,
      m.birthTime,
      (m.blueprint?.type || ''),
      (m.blueprint?.strategy || ''),
      (m.blueprint?.authority || '')
    ]);
    autoTable(doc, {
      head: [['Name', 'Relation', 'Birth Date', 'Birth Time', 'Type', 'Strategy', 'Authority']],
      body: rows,
      startY: 40,
    });
  }

  doc.save('relationship_user_manual.pdf');
}
